=== hafniz/ASCIIsome/ASCIIsome/Resources/CharSets/CharSetSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="CharSet">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="CharInfo">
          <xs:complexType>
            <xs:attribute name="GrayscaleIndex" type="xs:double" use="required" />
            <xs:attribute name="Character" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="DisplayName" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hafniz/ASCIIsome/ASCIIsome/Resources/CharSets/cs_LowercaseEnglishAlphabets.xml
<?xml version="1.0" encoding="utf-8" ?>
<CharSet DisplayName="Lowercase English alphabets" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ASCIIsome.Resources.CharSets CharSetSchema.xsd">
  <CharInfo GrayscaleIndex="0.21409" Character="a"/>
  <CharInfo GrayscaleIndex="0.26391" Character="b"/>
  <CharInfo GrayscaleIndex="0.15864" Character="c"/>
  <CharInfo GrayscaleIndex="0.26404" Character="d"/>
  <CharInfo GrayscaleIndex="0.21643" Character="e"/>
  <CharInfo GrayscaleIndex="0.19965" Character="f"/>
  <CharInfo GrayscaleIndex="0.28651" Character="g"/>
  <CharInfo GrayscaleIndex="0.24106" Character="h"/>
  <CharInfo GrayscaleIndex="0.13311" Character="i"/>
  <CharInfo GrayscaleIndex="0.19153" Character="j"/>
  <CharInfo GrayscaleIndex="0.22855" Character="k"/>
  <CharInfo GrayscaleIndex="0.14861" Character="l"/>
  <CharInfo GrayscaleIndex="0.25568" Character="m"/>
  <CharInfo GrayscaleIndex="0.20240" Character="n"/>
  <CharInfo GrayscaleIndex="0.21362" Character="o"/>
  <CharInfo GrayscaleIndex="0.25647" Character="p"/>
  <CharInfo GrayscaleIndex="0.25523" Character="q"/>
  <CharInfo GrayscaleIndex="0.13587" Character="r"/>
  <CharInfo GrayscaleIndex="0.17882" Character="s"/>
  <CharInfo GrayscaleIndex="0.17171" Character="t"/>
  <CharInfo GrayscaleIndex="0.20239" Character="u"/>
  <CharInfo GrayscaleIndex="0.15712" Character="v"/>
  <CharInfo GrayscaleIndex="0.23556" Character="w"/>
  <CharInfo GrayscaleIndex="0.18201" Character="x"/>
  <CharInfo GrayscaleIndex="0.19103" Character="y"/>
  <CharInfo GrayscaleIndex="0.18484" Character="z"/>
</CharSet>

=== hafniz/ASCIIsome/ASCIIsome/Resources/CharSets/cs_Numerals.xml
<?xml version="1.0" encoding="utf-8" ?>
<CharSet DisplayName="Numerals" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ASCIIsome.Resources.CharSets CharSetSchema.xsd">
  <CharInfo GrayscaleIndex="0.26270" Character="0"/>
  <CharInfo GrayscaleIndex="0.18531" Character="1"/>
  <CharInfo GrayscaleIndex="0.19975" Character="2"/>
  <CharInfo GrayscaleIndex="0.19922" Character="3"/>
  <CharInfo GrayscaleIndex="0.21424" Character="4"/>
  <CharInfo GrayscaleIndex="0.19647" Character="5"/>
  <CharInfo GrayscaleIndex="0.25800" Character="6"/>
  <CharInfo GrayscaleIndex="0.16855" Character="7"/>
  <CharInfo GrayscaleIndex="0.28226" Character="8"/>
  <CharInfo GrayscaleIndex="0.25795" Character="9"/>
</CharSet>

=== hafniz/ASCIIsome/ASCIIsome/Resources/CharSets/cs_UppercaseRussianAlphabets.xml
<?xml version="1.0" encoding="utf-8" ?>
<CharSet DisplayName="Uppercase Russian alphabets" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ASCIIsome.Resources.CharSets CharSetSchema.xsd">
  <CharInfo GrayscaleIndex="0.21229" Character="А"/>
  <CharInfo GrayscaleIndex="0.24278" Character="Б"/>
  <CharInfo GrayscaleIndex="0.27045" Character="В"/>
  <CharInfo GrayscaleIndex="0.14285" Character="Г"/>
  <CharInfo GrayscaleIndex="0.31134" Character="Д"/>
  <CharInfo GrayscaleIndex="0.21602" Character="Е"/>
  <CharInfo GrayscaleIndex="0.23992" Character="Ё"/>
  <CharInfo GrayscaleIndex="0.28596" Character="Ж"/>
  <CharInfo GrayscaleIndex="0.20904" Character="З"/>
  <CharInfo GrayscaleIndex="0.26244" Character="И"/>
  <CharInfo GrayscaleIndex="0.29582" Character="Й"/>
  <CharInfo GrayscaleIndex="0.21981" Character="К"/>
  <CharInfo GrayscaleIndex="0.22889" Character="Л"/>
  <CharInfo GrayscaleIndex="0.27128" Character="М"/>
  <CharInfo GrayscaleIndex="0.23306" Character="Н"/>
  <CharInfo GrayscaleIndex="0.24683" Character="О"/>
  <CharInfo GrayscaleIndex="0.23306" Character="П"/>
  <CharInfo GrayscaleIndex="0.21172" Character="Р"/>
  <CharInfo GrayscaleIndex="0.18769" Character="С"/>
  <CharInfo GrayscaleIndex="0.15891" Character="Т"/>
  <CharInfo GrayscaleIndex="0.18653" Character="У"/>
  <CharInfo GrayscaleIndex="0.26702" Character="Ф"/>
  <CharInfo GrayscaleIndex="0.20683" Character="Х"/>
  <CharInfo GrayscaleIndex="0.26478" Character="Ц"/>
  <CharInfo GrayscaleIndex="0.19706" Character="Ч"/>
  <CharInfo GrayscaleIndex="0.30418" Character="Ш"/>
  <CharInfo GrayscaleIndex="0.33191" Character="Щ"/>
  <CharInfo GrayscaleIndex="0.21800" Character="Ъ"/>
  <CharInfo GrayscaleIndex="0.27651" Character="Ы"/>
  <CharInfo GrayscaleIndex="0.20956" Character="Ь"/>
  <CharInfo GrayscaleIndex="0.22130" Character="Э"/>
  <CharInfo GrayscaleIndex="0.32982" Character="Ю"/>
  <CharInfo GrayscaleIndex="0.25545" Character="Я"/>
</CharSet>

=== hafniz/ASCIIsome/ASCIIsome/Resources/CharSets/cs_ASCIISymbols.xml
<?xml version="1.0" encoding="utf-8" ?>
<CharSet DisplayName="ASCII symbols" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ASCIIsome.Resources.CharSets CharSetSchema.xsd">
  <CharInfo GrayscaleIndex="0.00000" Character=" "/>
  <CharInfo GrayscaleIndex="0.09771" Character="!"/>
  <CharInfo GrayscaleIndex="0.08598" Character="&quot;"/>
  <CharInfo GrayscaleIndex="0.26690" Character="#"/>
  <CharInfo GrayscaleIndex="0.24652" Character="$"/>
  <CharInfo GrayscaleIndex="0.26139" Character="%"/>
  <CharInfo GrayscaleIndex="0.32644" Character="&amp;"/>
  <CharInfo GrayscaleIndex="0.06079" Character="&apos;"/>
  <CharInfo GrayscaleIndex="0.15888" Character="("/>
  <CharInfo GrayscaleIndex="0.15899" Character=")"/>
  <CharInfo GrayscaleIndex="0.10613" Character="*"/>
  <CharInfo GrayscaleIndex="0.11651" Character="+"/>
  <CharInfo GrayscaleIndex="0.05551" Character=","/>
  <CharInfo GrayscaleIndex="0.04805" Character="-"/>
  <CharInfo GrayscaleIndex="0.03526" Character="."/>
  <CharInfo GrayscaleIndex="0.12511" Character="/"/>
  <CharInfo GrayscaleIndex="0.07051" Character=":"/>
  <CharInfo GrayscaleIndex="0.09098" Character=";"/>
  <CharInfo GrayscaleIndex="0.11943" Character="&lt;"/>
  <CharInfo GrayscaleIndex="0.12557" Character="="/>
  <CharInfo GrayscaleIndex="0.11959" Character="&gt;"/>
  <CharInfo GrayscaleIndex="0.15773" Character="?"/>
  <CharInfo GrayscaleIndex="0.29367" Character="@"/>
  <CharInfo GrayscaleIndex="0.18132" Character="["/>
  <CharInfo GrayscaleIndex="0.12511" Character="\"/>
  <CharInfo GrayscaleIndex="0.18132" Character="]"/>
  <CharInfo GrayscaleIndex="0.13303" Character="^"/>
  <CharInfo GrayscaleIndex="0.07293" Character="_"/>
  <CharInfo GrayscaleIndex="0.01924" Character="`"/>
  <CharInfo GrayscaleIndex="0.17471" Character="{"/>
  <CharInfo GrayscaleIndex="0.11072" Character="|"/>
  <CharInfo GrayscaleIndex="0.17472" Character="}"/>
  <CharInfo GrayscaleIndex="0.07732" Character="~"/>
</CharSet>

=== hafniz/ASCIIsome/ASCIIsome/Resources/CharSets/cs_LowercaseRussianAlphabets.xml
<?xml version="1.0" encoding="utf-8" ?>
<CharSet DisplayName="Lowercase Russian alphabets" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ASCIIsome.Resources.CharSets CharSetSchema.xsd">
  <CharInfo GrayscaleIndex="0.21409" Character="а"/>
  <CharInfo GrayscaleIndex="0.28532" Character="б"/>
  <CharInfo GrayscaleIndex="0.23818" Character="в"/>
  <CharInfo GrayscaleIndex="0.12600" Character="г"/>
  <CharInfo GrayscaleIndex="0.26104" Character="д"/>
  <CharInfo GrayscaleIndex="0.21638" Character="е"/>
  <CharInfo GrayscaleIndex="0.24028" Character="ё"/>
  <CharInfo GrayscaleIndex="0.23565" Character="ж"/>
  <CharInfo GrayscaleIndex="0.17241" Character="з"/>
  <CharInfo GrayscaleIndex="0.22485" Character="и"/>
  <CharInfo GrayscaleIndex="0.26698" Character="й"/>
  <CharInfo GrayscaleIndex="0.17971" Character="к"/>
  <CharInfo GrayscaleIndex="0.19101" Character="л"/>
  <CharInfo GrayscaleIndex="0.24651" Character="м"/>
  <CharInfo GrayscaleIndex="0.19864" Character="н"/>
  <CharInfo GrayscaleIndex="0.21368" Character="о"/>
  <CharInfo GrayscaleIndex="0.19646" Character="п"/>
  <CharInfo GrayscaleIndex="0.25652" Character="р"/>
  <CharInfo GrayscaleIndex="0.15858" Character="с"/>
  <CharInfo GrayscaleIndex="0.13771" Character="т"/>
  <CharInfo GrayscaleIndex="0.19103" Character="у"/>
  <CharInfo GrayscaleIndex="0.32498" Character="ф"/>
  <CharInfo GrayscaleIndex="0.18200" Character="х"/>
  <CharInfo GrayscaleIndex="0.22578" Character="ц"/>
  <CharInfo GrayscaleIndex="0.16197" Character="ч"/>
  <CharInfo GrayscaleIndex="0.26258" Character="ш"/>
  <CharInfo GrayscaleIndex="0.28888" Character="щ"/>
  <CharInfo GrayscaleIndex="0.18789" Character="ъ"/>
  <CharInfo GrayscaleIndex="0.24428" Character="ы"/>
  <CharInfo GrayscaleIndex="0.17799" Character="ь"/>
  <CharInfo GrayscaleIndex="0.18359" Character="э"/>
  <CharInfo GrayscaleIndex="0.27440" Character="ю"/>
  <CharInfo GrayscaleIndex="0.21188" Character="я"/>
</CharSet>
